{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\dito\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\tqdm\\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n"
     ]
    }
   ],
   "source": [
    "#!pip install pyodbc\n",
    "#!pip install pandas_profiling\n",
    "#!pip install pandas\n",
    "\n",
    "import pandas as pd\n",
    "import pyodbc\n",
    "import ydata_profiling"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "sql_conn = pyodbc.connect('DRIVER={SQL Server}; \\\n",
    "                            SERVER=LAPTOP-1NTPD1QL\\SQLEXPRESS; \\\n",
    "                            DATABASE=OLTP_PenerimaanMandiri; \\\n",
    "                            Trusted_Connection=yes') "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 47/47 [00:10<00:00,  4.39it/s, Completed]                            \n",
      "Generate report structure: 100%|██████████| 1/1 [00:05<00:00,  5.52s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.42s/it]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 84.87it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 12/12 [00:00<00:00, 35.17it/s, Completed]               \n",
      "Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.27it/s]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 284.07it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 19/19 [00:00<00:00, 22.66it/s, Completed]                                       \n",
      "Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.20s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  4.39it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 200.01it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 11/11 [00:00<00:00, 45.44it/s, Completed]               \n",
      "Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.57it/s]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00, 16.72it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 278.04it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 11/11 [00:00<00:00, 45.42it/s, Completed]               \n",
      "Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.55it/s]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00, 15.84it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 13/13 [00:00<00:00, 35.76it/s, Completed]                  \n",
      "Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.31it/s]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 998.88it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 11/11 [00:00<00:00, 51.78it/s, Completed]                   \n",
      "Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00, 16.77it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 1002.22it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 13/13 [00:00<00:00, 34.44it/s, Completed]                \n",
      "Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.14it/s]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 457.19it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 16/16 [00:00<00:00, 19.80it/s, Completed]                         \n",
      "Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.15it/s]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 499.92it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 16/16 [00:01<00:00, 14.44it/s, Completed]                \n",
      "Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.10s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  6.82it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 500.16it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 141/141 [00:12<00:00, 11.00it/s, Completed]                               \n",
      "Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.68s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.17it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 153.52it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 11/11 [00:00<00:00, 54.23it/s, Completed]                       \n",
      "Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.79it/s]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00, 16.73it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 999.60it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 12/12 [00:00<00:00, 21.43it/s, Completed]                  \n",
      "Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.60it/s]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00, 14.49it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 998.41it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 29/29 [00:01<00:00, 16.06it/s, Completed]                           \n",
      "Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.07s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  5.35it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 499.68it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 11/11 [00:00<00:00, 51.77it/s, Completed]               \n",
      "Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.71it/s]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00, 15.70it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 500.33it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 16/16 [00:00<00:00, 25.17it/s, Completed]                 \n",
      "Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.13it/s]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 501.05it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 14/14 [00:00<00:00, 37.70it/s, Completed]                          \n",
      "Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.22s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 1008.25it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 12/12 [00:00<00:00, 46.78it/s, Completed]                    \n",
      "Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.03s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 663.97it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 21/21 [00:00<00:00, 24.91it/s, Completed]                         \n",
      "Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.64s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  4.55it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 324.99it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 54/54 [00:04<00:00, 11.87it/s, Completed]                               \n",
      "Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.13s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.43it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 181.14it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 13/13 [00:00<00:00, 41.28it/s, Completed]                       \n",
      "Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.41s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 971.58it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 23/23 [00:01<00:00, 15.07it/s, Completed]                               \n",
      "Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.29s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  5.65it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 1000.07it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset:  36%|███▋      | 4/11 [00:00<00:00, 37.05it/s, Describe variable:NamaAyah]C:\\Users\\dito\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\ydata_profiling\\model\\typeset_relations.py:117: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.\n",
      "  return pd.to_datetime(series)\n",
      "C:\\Users\\dito\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\ydata_profiling\\model\\typeset_relations.py:117: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.\n",
      "  return pd.to_datetime(series)\n",
      "Summarize dataset:  36%|███▋      | 4/11 [00:00<00:00, 37.05it/s, Describe variable:TempatLahir]C:\\Users\\dito\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\ydata_profiling\\model\\typeset_relations.py:117: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.\n",
      "  return pd.to_datetime(series)\n",
      "C:\\Users\\dito\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\ydata_profiling\\model\\typeset_relations.py:117: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.\n",
      "  return pd.to_datetime(series)\n",
      "C:\\Users\\dito\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\ydata_profiling\\model\\typeset_relations.py:117: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.\n",
      "  return pd.to_datetime(series)\n",
      "Summarize dataset: 100%|██████████| 19/19 [00:00<00:00, 22.75it/s, Completed]                           \n",
      "Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.25s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  4.75it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 284.22it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset:  18%|█▊        | 2/11 [00:00<00:00, 54.50it/s, Describe variable:Ibu_ID]   C:\\Users\\dito\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\ydata_profiling\\model\\typeset_relations.py:117: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.\n",
      "  return pd.to_datetime(series)\n",
      "C:\\Users\\dito\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\ydata_profiling\\model\\typeset_relations.py:117: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.\n",
      "  return pd.to_datetime(series)\n",
      "Summarize dataset:  36%|███▋      | 4/11 [00:00<00:00, 35.51it/s, Describe variable:TempatLahir]C:\\Users\\dito\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\ydata_profiling\\model\\typeset_relations.py:117: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.\n",
      "  return pd.to_datetime(series)\n",
      "C:\\Users\\dito\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\ydata_profiling\\model\\typeset_relations.py:117: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.\n",
      "  return pd.to_datetime(series)\n",
      "Summarize dataset: 100%|██████████| 19/19 [00:01<00:00, 18.97it/s, Completed]                    \n",
      "Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  5.30it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 250.00it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 107/107 [00:12<00:00,  8.91it/s, Completed]                          \n",
      "Generate report structure: 100%|██████████| 1/1 [00:06<00:00,  6.02s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.06s/it]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 79.90it/s]\n",
      "C:\\Users\\dito\\AppData\\Local\\Temp\\ipykernel_25404\\2888492151.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(sql_query, sql_conn)\n",
      "Summarize dataset: 100%|██████████| 42/42 [00:03<00:00, 13.85it/s, Completed]                               \n",
      "Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it]\n",
      "Render HTML: 100%|██████████| 1/1 [00:00<00:00,  3.21it/s]\n",
      "Export report to file: 100%|██████████| 1/1 [00:00<00:00, 333.33it/s]\n"
     ]
    }
   ],
   "source": [
    "cursor = sql_conn.cursor()\n",
    "cursor.execute(\"SELECT table_schema, table_name FROM information_schema.tables WHERE table_type = 'BASE TABLE' AND TABLE_CATALOG='OLTP_PenerimaanMandiri'\")\n",
    "schemas_and_tables = cursor.fetchall()\n",
    "\n",
    "for schema, table in schemas_and_tables:\n",
    "    sql_query = f\"SELECT * FROM {schema}.{table}\"\n",
    "    try:\n",
    "        df = pd.read_sql(sql_query, sql_conn)\n",
    "        report = ydata_profiling.ProfileReport(df)\n",
    "        report.to_file(f\"C:/Users/dito/Downloads/{schema}_{table}_profile_report.html\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error processing table {schema}.{table}: {e}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
